# Generated by Django 3.1.6 on 2021-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=255)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('variety', models.CharField(max_length=255, null=True)),
                ('level_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
