# Generated by Django 3.1.6 on 2021-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='level_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
